import {writeFileSync,mkdirSync} from 'node:fs';
let seed=123456789; const random=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return (seed+1)/4294967297;};
function simulate(rate){let difficulty=65536,time=0,window=0,maxWait=0;for(let id=1;id<=16384;id++){const h=typeof rate==='function'?rate(id):rate;const wait=-Math.log(random())*difficulty/h;time+=wait;window+=wait;maxWait=Math.max(maxWait,wait);if(id%8===0){difficulty=Math.max(65536,difficulty*480/Math.max(240,Math.min(960,window)));window=0;}}return {days:time/86400,longestGlobalGapHours:maxWait/3600};}
const results=[];
for(const [name,rate] of [['100 kH/s',1e5],['1 MH/s',1e6],['100 MH/s',1e8],['10 GH/s',1e10],['100 MH/s then 100 kH/s after mint 8192',id=>id<=8192?1e8:1e5]]){const runs=Array.from({length:100},()=>simulate(rate));const days=runs.map(r=>r.days).sort((a,b)=>a-b);results.push({scenario:name,runs:100,medianDays:days[50],p05Days:days[5],p95Days:days[95],worstGlobalGapHours:Math.max(...runs.map(r=>r.longestGlobalGapHours))});}
let reward=1000n*10n**18n;const rewards=[];for(let i=0;i<=32;i++){rewards.push(reward);reward=reward*95n/100n;}
const immediate=511n*rewards[0]+rewards.slice(1,32).reduce((a,b)=>a+512n*b,0n)+rewards[32];
const report={assumptions:'Seeded Monte Carlo: exponential independent hash search; constant effective total hashrate except named shock. No network latency, stale work, wallet delay, fees, demand or transaction contention. Recovery only after 8 accepted mints. Not a forecast.',results,rewardAtFinalEpochBCAT:Number(rewards[32])/1e18,illustrativeImmediateBurnIssuanceBCAT:Number(immediate)/1e18,conservativeRewardUpperBoundBCAT:16384000,communityReserveBCAT:1000000};
mkdirSync('reports',{recursive:true});writeFileSync('reports/mining-simulation.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
